# Kubernetes Setup for {{ $config->getName() }}

This project was crafted using **LaraKube**. it provides an opinionated, professional-grade Kubernetes infrastructure following a "Zero-Host" philosophy.

## 🚀 Quick Start

1. **Trust** the LaraKube Local CA: `larakube trust` (Once per machine).
2. **Setup** your `/etc/hosts` file for `https://{{ $config->getWebHost('local') }}`.
3. **Deploy** the application: `larakube up`.

## 🛠 Available Commands

- **Deploy:** `larakube up` (Builds, pushes, and applies manifests).
- **Destroy:** `larakube down` (Wipes all resources from the cluster).
- **Execute:** `larakube exec "php artisan migrate"` (Runs commands inside the pod).
- **Logs:** `larakube logs` (Streams application logs).
- **Status:** `larakube status` (Shows health of all components).

## 📂 Architecture Overview

### Stacks
- **PHP:** {{ $config->getPhpVersion()->value }} ({{ $config->getServerVariation()->value }})
- **OS:** {{ $config->getOs()->value }}

### Components
@foreach($config->getComponents() as $component)
- {{ $component->getLabel() }}
@endforeach

## 🌐 URLs

@foreach($config->getAllHosts() as $host => $description)
- **{{ $description }}:** https://{{ $host }}
@endforeach

---
*Generated by LaraKube - Architectural Excellence for Laravel.*
